grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
    class: KNeighborsClassifier
    module: sklearn.neighbors
    params:
      algorithm: kd_tree
      weights: uniform
      n_neighbors: 3
    search_param_grid:
      algorithm:
      - auto
      - ball_tree
      - kd_tree
      - brute
      weights:
      - uniform
      - distance
      n_neighbors:
      - 3
      - 5
      - 7

      
  # module_1:
  #   class: RandomForestClassifier
  #   module: sklearn.ensemble
  #   params:
  #     max_depth: 120
  #     max_features: sqrt
  #     n_estimators: 1700
  #   search_param_grid:
  #     max_depth:
  #     - 120
  #     - 150
  #     - 170
  #     max_features:
  #     - sqrt
  #     - log2
  #     n_estimators:
  #     - 1200
  #     - 1500
  #     - 1700
  #     criterion: 
  #     - entropy
  #     - gini